sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "8"
after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
    - master
